# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully!")

Libraries imported successfully!

# Load Dataset

In [9]:
df = pd.read_excel("C:/Users/hp/OneDrive/Desktop/market-basket-analysis/data/Online Retail.xlsx")
print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (541909, 8)

In [10]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

# Columns Check

In [11]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

# Data Information

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [13]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [15]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

# Step 3 — Missing Values

In [16]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [17]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

missing_summary

             Missing Values  Percentage
InvoiceNo                 0        0.00
StockCode                 0        0.00
Description            1454        0.27
Quantity                  0        0.00
InvoiceDate               0        0.00
UnitPrice                 0        0.00
CustomerID           135080       24.93
Country                   0        0.00

# Step 4 — Duplicate Records

In [18]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 5268

In [19]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (536641, 8)

# Step 5 — InvoiceDate Convert

In [23]:
df = df.copy()

df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    errors="coerce"
)

print(df["InvoiceDate"].dtype)

datetime64[ns]

In [24]:
df = df.drop_duplicates()

In [25]:
df = df[df["Quantity"] > 0]

In [26]:
cancelled_orders = df[
    df["InvoiceNo"].astype(str).str.startswith("C")
]

print("Cancelled orders:", len(cancelled_orders))

Cancelled orders: 0

# 1. Cancelled Orders Remove

In [27]:
cancelled_orders = df[
    df["InvoiceNo"].astype(str).str.startswith("C")
]

print("Cancelled orders:", len(cancelled_orders))

Cancelled orders: 0

In [28]:
df = df[
    ~df["InvoiceNo"].astype(str).str.startswith("C")
].copy()

print("Shape after removing cancelled orders:", df.shape)

Shape after removing cancelled orders: (526054, 8)

# 2. Check Invalid Quantity

In [29]:
print("Quantity <= 0:", (df["Quantity"] <= 0).sum())

Quantity <= 0: 0

# 3. Remove Invalid Quantity

In [30]:
df = df[df["Quantity"] > 0].copy()

print("Shape after removing invalid quantity:", df.shape)

Shape after removing invalid quantity: (526054, 8)

# 4. Check Invalid Unit Price

In [31]:
print("UnitPrice <= 0:", (df["UnitPrice"] <= 0).sum())

UnitPrice <= 0: 1176

# 5. Remove Invalid Unit Price

In [32]:
df = df[df["UnitPrice"] > 0].copy()

print("Shape after removing invalid prices:", df.shape)

Shape after removing invalid prices: (524878, 8)

# 6. Check Missing CustomerID

In [33]:
print("Missing CustomerID:", df["CustomerID"].isnull().sum())

Missing CustomerID: 132186

# 7. Remove Missing CustomerID

In [34]:
df = df.dropna(subset=["CustomerID"]).copy()

print("Shape after removing missing CustomerID:", df.shape)

Shape after removing missing CustomerID: (392692, 8)

# 8. Convert CustomerID to Integer

In [35]:
df["CustomerID"] = df["CustomerID"].astype(int)

print(df["CustomerID"].dtype)

int64

# 9. Create Revenue

In [36]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

df[
    ["Quantity", "UnitPrice", "Revenue"]
].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

# 10. Check Revenue

In [37]:
print("Total Revenue:", round(df["Revenue"].sum(), 2))
print("Minimum Revenue:", df["Revenue"].min())
print("Maximum Revenue:", df["Revenue"].max())

Total Revenue: 8887208.89
Minimum Revenue: 0.001
Maximum Revenue: 168469.6

# 11. Extract Year

In [38]:
df["Year"] = df["InvoiceDate"].dt.year

# 12. Extract Month

In [39]:
df["Month"] = df["InvoiceDate"].dt.month

# 13. Extract Day

In [40]:
df["Day"] = df["InvoiceDate"].dt.day

# 14. Extract Hour

In [41]:
df["Hour"] = df["InvoiceDate"].dt.hour

# 15. Extract Day of Week

In [42]:
df["DayOfWeek"] = df["InvoiceDate"].dt.day_name()

# 16. Check New Features

In [43]:
df[
    [
        "InvoiceDate",
        "Year",
        "Month",
        "Day",
        "Hour",
        "DayOfWeek",
        "Revenue"
    ]
].head()

          InvoiceDate  Year  Month  Day  Hour  DayOfWeek  Revenue
0 2010-12-01 08:26:00  2010     12    1     8  Wednesday    15.30
1 2010-12-01 08:26:00  2010     12    1     8  Wednesday    20.34
2 2010-12-01 08:26:00  2010     12    1     8  Wednesday    22.00
3 2010-12-01 08:26:00  2010     12    1     8  Wednesday    20.34
4 2010-12-01 08:26:00  2010     12    1     8  Wednesday    20.34

# 17. Create Year-Month Feature

In [44]:
df["YearMonth"] = df["InvoiceDate"].dt.to_period("M")

df[
    ["InvoiceDate", "YearMonth"]
].head()

          InvoiceDate YearMonth
0 2010-12-01 08:26:00   2010-12
1 2010-12-01 08:26:00   2010-12
2 2010-12-01 08:26:00   2010-12
3 2010-12-01 08:26:00   2010-12
4 2010-12-01 08:26:00   2010-12

# 18. Final Dataset Shape

In [45]:
print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (392692, 15)

# 19. Final Columns

In [46]:
print("Final Columns:")

for column in df.columns:
    print("-", column)

Final Columns:
- InvoiceNo
- StockCode
- Description
- Quantity
- InvoiceDate
- UnitPrice
- CustomerID
- Country
- Revenue
- Year
- Month
- Day
- Hour
- DayOfWeek
- YearMonth

# 20. Final Missing Values Check

In [47]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing_summary

             Missing Values  Missing Percentage
InvoiceNo                 0                 0.0
StockCode                 0                 0.0
Description               0                 0.0
Quantity                  0                 0.0
InvoiceDate               0                 0.0
UnitPrice                 0                 0.0
CustomerID                0                 0.0
Country                   0                 0.0
Revenue                   0                 0.0
Year                      0                 0.0
Month                     0                 0.0
Day                       0                 0.0
Hour                      0                 0.0
DayOfWeek                 0                 0.0
YearMonth                 0                 0.0

# 21. Final Duplicate Check

In [48]:
print("Duplicate Records:", df.duplicated().sum())

Duplicate Records: 0

# 22. Final Data Preview

In [50]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,Day,Hour,DayOfWeek,YearMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,8,Wednesday,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,1,8,Wednesday,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010-12

# 23. Dataset Statistics

In [51]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID,Revenue,Year,Month,Day,Hour
count,392692.000000,392692,392692.000000,392692.000000,392692.000000,392692.000000,392692.000000,392692.000000,392692.000000
mean,13.119702,2011-07-10 19:13:07.771892480,3.125914,15287.843865,22.631500,2010.934631,7.601871,15.044656,12.721532
min,1.000000,2010-12-01 08:26:00,0.001000,12346.000000,0.001000,2010.000000,1.000000,1.000000,6.000000
25%,2.000000,2011-04-07 11:12:00,1.250000,13955.000000,4.950000,2011.000000,5.000000,7.000000,11.000000
50%,6.000000,2011-07-31 12:02:00,1.950000,15150.000000,12.450000,2011.000000,8.000000,15.000000,13.000000
75%,12.000000,2011-10-20 12:53:00,3.750000,16791.000000,19.800000,2011.000000,11.000000,22.000000,14.000000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000,168469.600000,2011.000000,12.000000,31.000000,20.000000
std,180.492832,NaN,22.241836,1713.539549,311.099224,0.247177,3.415015,8.652532,2.276661

# 24. Important Business Metrics

In [52]:
total_revenue = df["Revenue"].sum()
total_customers = df["CustomerID"].nunique()
total_orders = df["InvoiceNo"].nunique()
total_products = df["StockCode"].nunique()
total_countries = df["Country"].nunique()

print("Total Revenue:", round(total_revenue, 2))
print("Total Customers:", total_customers)
print("Total Orders:", total_orders)
print("Total Products:", total_products)
print("Total Countries:", total_countries)

Total Revenue: 8887208.89
Total Customers: 4338
Total Orders: 18532
Total Products: 3665
Total Countries: 37

# 25. Average Order Value

In [53]:
average_order_value = (
    df.groupby("InvoiceNo")["Revenue"]
    .sum()
    .mean()
)

print(
    "Average Order Value:",
    round(average_order_value, 2)
)

Average Order Value: 479.56

# 26. Check Date Range

In [54]:
print("First Transaction:", df["InvoiceDate"].min())
print("Last Transaction:", df["InvoiceDate"].max())

First Transaction: 2010-12-01 08:26:00
Last Transaction: 2011-12-09 12:50:00

# 27. Top 10 Countries by Revenue

In [55]:
top_countries = (
    df.groupby("Country")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_countries

Country
United Kingdom    7285024.644
Netherlands        285446.340
EIRE               265262.460
Germany            228678.400
France             208934.310
Australia          138453.810
Spain               61558.560
Switzerland         56443.950
Belgium             41196.340
Sweden              38367.830
Name: Revenue, dtype: float64

# 28. Top 10 Products by Revenue

In [57]:
top_products = (
    df.groupby("Description")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products

Description
PAPER CRAFT , LITTLE BIRDIE           168469.60
REGENCY CAKESTAND 3 TIER              142264.75
WHITE HANGING HEART T-LIGHT HOLDER    100392.10
JUMBO BAG RED RETROSPOT                85040.54
MEDIUM CERAMIC TOP STORAGE JAR         81416.73
POSTAGE                                77803.96
PARTY BUNTING                          68785.23
ASSORTED COLOUR BIRD ORNAMENT          56413.03
Manual                                 53419.93
RABBIT NIGHT LIGHT                     51251.24
Name: Revenue, dtype: float64

# 29. Save Cleaned Dataset

In [58]:
output_path = "../data/cleaned_online_retail.csv"

df.to_csv(
    output_path,
    index=False
)

print("Cleaned dataset saved successfully!")
print("File:", output_path)

Cleaned dataset saved successfully!
File: ../data/cleaned_online_retail.csv

# 30. Verify Saved File

In [59]:
cleaned_df = pd.read_csv(
    "../data/cleaned_online_retail.csv"
)

print("Cleaned file loaded successfully!")
print("Shape:", cleaned_df.shape)

cleaned_df.head()

Cleaned file loaded successfully!
Shape: (392692, 15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,Day,Hour,DayOfWeek,YearMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010,12,1,8,Wednesday,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010,12,1,8,Wednesday,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010,12,1,8,Wednesday,2010-12

In [60]:
cleaned_df = pd.read_csv("../data/cleaned_online_retail.csv")

print("Cleaned file loaded successfully!")
print("Shape:", cleaned_df.shape)

Cleaned file loaded successfully!
Shape: (392692, 15)